# -------------------------------------------------------------------------------------
# Hugo Configuration
# See: https://gohugo.io/getting-started/configuration/
# -------------------------------------------------------------------------------------

title = "刘十五"
baseURL = "https://blog.thinktechly.cn"
# theme = "FixIt"
defaultContentLanguage = "zh-cn"
languageCode = "zh-CN"
hasCJKLanguage = true
enableRobotsTXT = true
enableEmoji = true
enableGitInfo = true
relativeURLs = false
buildDrafts = false
summaryLength = 150
# ignore some build errors
ignoreLogs = [
  "error-get-remote-image",
  "error-get-remote-json",
  "error-remote-getjson",
  "error-missing-instagram-accesstoken"
]

# 添加以下多语言配置
# 如果希望默认语言也显示在URL中，设置为true
defaultContentLanguageInSubdir = true

[languages]
  [languages.zh-cn]
    weight = 1
    title = "刘十五"
    languageName = "简体中文"
    # 可以为每种语言设置不同的菜单
    # [languages.zh-cn.menu]
    #   [[languages.zh-cn.menu.main]]
    #     identifier = "posts"
    #     name = "文章"
    #     url = "/posts/"
    #     weight = 1

  [languages.en]
    weight = 2
    title = "Liu Fifteen"
    languageName = "English"
    # [languages.en.menu]
    #   [[languages.en.menu.main]]
    #     identifier = "posts"
    #     name = "Posts"
    #     url = "/posts/"
    #     weight = 1


[module]
  [[module.imports]]
    path = "github.com/hugo-fixit/fixit-bundle"
  [[module.imports]]
    path = "github.com/hugo-fixit/cmpt-translate"


[params.customPartials]
head = []
menuDesktop = [ "inject/translate-menu-desktop.html", ]
menuMobile = [ "inject/translate-menu-mobile.html", ]
profile = []
aside = []
comment = []
footer = []
widgets = []
assets = [ "inject/cmpt-translate.html", ]
postFooterBefore = []
postFooterAfter = []