# -------------------------------------------------------------------------------------
# Hugo Configuration
# See: https://gohugo.io/getting-started/configuration/
# -------------------------------------------------------------------------------------

title = "刘十五"
baseURL = "https://blog.thinktechly.cn"
# theme = "FixIt"
defaultContentLanguage = "zh-cn"
languageCode = "zh-CN"
hasCJKLanguage = true
enableRobotsTXT = true
enableEmoji = true
enableGitInfo = true
relativeURLs = false
buildDrafts = false
summaryLength = 150
# ignore some build errors
ignoreLogs = [
  "error-get-remote-image",
  "error-get-remote-json",
  "error-remote-getjson",
  "error-missing-instagram-accesstoken"
]

# 添加以下多语言配置
# 如果希望默认语言也显示在URL中，设置为true
defaultContentLanguageInSubdir = true

[languages]
  [languages.zh-cn]
    weight = 1
    title = "刘十五"
    languageName = "简体中文"
    # 中文菜单配置
    [languages.zh-cn.menu]
      [[languages.zh-cn.menu.main]]
        identifier = "archives"
        name = "归档"
        url = "/archives/"
        weight = 1
        [languages.zh-cn.menu.main.params]
          icon = "fa-solid fa-archive"
      [[languages.zh-cn.menu.main]]
        identifier = "categories"
        name = "分类"
        url = "/categories/"
        weight = 2
        [languages.zh-cn.menu.main.params]
          icon = "fa-solid fa-folder-tree"
      [[languages.zh-cn.menu.main]]
        identifier = "tags"
        name = "标签"
        url = "/tags/"
        weight = 3
        [languages.zh-cn.menu.main.params]
          icon = "fa-solid fa-tags"

  [languages.en]
    weight = 2
    title = "Liu Fifteen"
    languageName = "English"
    # 英文菜单配置
    [languages.en.menu]
      [[languages.en.menu.main]]
        identifier = "archives"
        name = "Archives"
        url = "/archives/"
        weight = 1
        [languages.en.menu.main.params]
          icon = "fa-solid fa-archive"
      [[languages.en.menu.main]]
        identifier = "categories"
        name = "Categories"
        url = "/categories/"
        weight = 2
        [languages.en.menu.main.params]
          icon = "fa-solid fa-folder-tree"
      [[languages.en.menu.main]]
        identifier = "tags"
        name = "Tags"
        url = "/tags/"
        weight = 3
        [languages.en.menu.main.params]
          icon = "fa-solid fa-tags"


[module]
  [[module.imports]]
    path = "github.com/hugo-fixit/fixit-bundle"
  [[module.imports]]
    path = "github.com/hugo-fixit/cmpt-translate"


[params.customPartials]
head = [
  "inject/fixit-docs-bookmark.html",
  "inject/cmpt-translate-config.html",
]
menuDesktop = [ "inject/translate-menu-desktop.html", ]
menuMobile = [ "inject/translate-menu-mobile.html", ]
profile = []
aside = []
comment = []
footer = []
widgets = []
assets = [ "inject/cmpt-translate.html", ]
postFooterBefore = []
postFooterAfter = []